targets:
  $default:
    auto_apply_builders: true
    builders:
      catalyst_builder|buildServiceProvider:
        options:
          providerClassName: 'DefaultServiceProvider'
          includePackageDependencies: true
      event_dispatcher_builder|buildEventDispatcher:
        options:
          eventDispatcherClassName: 'DefaultEventDispatcher'
          includePackageDependencies: true