name: ctwebdev2023
description: Modulare Flutter Apps Demo
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  intl: ^0.18.1

  ctwebdev2023_shared:
    path: 'packages/shared'

  ctwebdev2023_tasks:
    path: 'packages/tasks'

  ctwebdev2023_time_tracking:
    path: 'packages/time_tracking'

  ctwebdev2023_reporting:
    path: 'packages/reporting'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
